import { StyleSheet } from 'react-native';
import { COLORS } from '../owner/ownerTheme';

/** Field/button/modal/card styles shared across CompanyDetailScreen and its extracted pieces. */
export const sharedStyles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    gap: 14,
  },
  sectionTitle: { fontSize: 15.5, fontWeight: '700', color: COLORS.black, textAlign: 'right' },
  sectionHeaderRow: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' },
  addSmallButton: { flexDirection: 'row-reverse', alignItems: 'center', gap: 3 },
  addSmallButtonText: { fontSize: 13, fontWeight: '600', color: COLORS.blue },
  emptyText: { fontSize: 13, color: COLORS.grayLight, textAlign: 'center', paddingVertical: 8 },
  logoPicker: {
    height: 90,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    backgroundColor: COLORS.fieldBg,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  logoPickerText: { fontSize: 13, color: COLORS.gray },
  logoPreviewWrap: { width: 52, height: 52 },
  logoPreview: {
    width: 52,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  logoUploadedBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: COLORS.activeText,
    borderWidth: 2,
    borderColor: COLORS.fieldBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoPickerChangeText: { fontSize: 12, color: COLORS.blue, fontWeight: '600', marginTop: 6 },
  companyTypeRow: { flexDirection: 'row-reverse', gap: 9 },
  companyTypeChip: {
    flex: 1,
    height: 44,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.fieldBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  companyTypeChipActive: { borderColor: COLORS.blue, backgroundColor: COLORS.blue },
  companyTypeChipText: { fontSize: 13.5, fontWeight: '600', color: COLORS.gray },
  companyTypeChipTextActive: { color: COLORS.white },
  fieldGroup: { gap: 7 },
  fieldLabel: { fontSize: 12.5, fontWeight: '600', color: COLORS.gray, textAlign: 'right' },
  fieldInput: {
    height: 46,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.fieldBg,
    fontSize: 15,
    color: COLORS.black,
    paddingHorizontal: 14,
  },
  fieldInputLtr: { textAlign: 'left' },
  fieldInputError: { borderColor: COLORS.red },
  fieldInputMatch: { borderColor: COLORS.activeText },
  fieldErrorText: { fontSize: 11.5, color: COLORS.red, textAlign: 'right' },
  fieldInputWithIcon: {
    height: 46,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.fieldBg,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  fieldInputInner: {
    flex: 1,
    fontSize: 15,
    color: COLORS.black,
  },
  errorText: { color: COLORS.red, fontSize: 13, textAlign: 'center' },
  primaryButton: {
    height: 46,
    borderRadius: 11,
    backgroundColor: COLORS.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: { opacity: 0.7 },
  primaryButtonText: { color: COLORS.white, fontSize: 14.5, fontWeight: '600' },
  deleteHeaderRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 11 },
  deleteIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: COLORS.disabledBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteTitle: { fontSize: 17, fontWeight: '700', color: COLORS.black, textAlign: 'right' },
  deleteDescription: { fontSize: 13.5, color: COLORS.gray, lineHeight: 21, textAlign: 'right' },
  deleteBold: { color: COLORS.black, fontWeight: '600' },
  deleteButtonsRow: { flexDirection: 'row', gap: 9 },
  cancelButton: {
    flex: 1,
    height: 46,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: { color: COLORS.black, fontSize: 14.5, fontWeight: '600' },
  deleteButton: {
    flex: 1.3,
    height: 46,
    borderRadius: 11,
    backgroundColor: COLORS.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButtonDisabled: { backgroundColor: '#EDD9D6' },
  deleteButtonText: { color: COLORS.white, fontSize: 14.5, fontWeight: '600' },
  deleteButtonTextDisabled: { color: '#C39B95' },
});
