import React, { useCallback, useEffect, useState } from 'react';
import { Alert, StyleSheet, TouchableOpacity, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AppText, ErrorState, LoadingState } from '../../components/ui';
import { AdminGradientBackground } from '../../components/admin/AdminGradientBackground';
import { ExportReportSheet } from '../../components/fleet/ExportReportSheet';
import { useCompany } from '../../lib/CompanyContext';
import { listDrivers, listVehicles, listComplianceForOwners, listActiveVehicleDriversForVehicles, type DriverRow, type Vehicle, type ComplianceItem, type VehicleDriverWithProfile } from '../../lib/adminApi';
import { REPORT_CATEGORIES, exportDriversReport, type ReportCategory } from '../../lib/driverReport';
import { VEHICLE_REPORT_CATEGORIES, exportVehiclesReport, type VehicleReportCategory } from '../../lib/vehicleReport';
import { RootStackParamList } from '../../navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'Reports'>;
export default function ReportsScreen({ navigation }: Props) {
  const { companyId, company } = useCompany(); const insets = useSafeAreaInsets();
  const [drivers, setDrivers] = useState<DriverRow[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [compliance, setCompliance] = useState<Map<string, ComplianceItem[]>>(new Map()); const [assignments, setAssignments] = useState<Map<string, VehicleDriverWithProfile[]>>(new Map());
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [kind, setKind] = useState<'drivers' | 'vehicles' | null>(null); const [exporting, setExporting] = useState<string | null>(null);
  const load = useCallback(async () => { if (!companyId) { setError('לא נמצאה חברה משויכת'); setLoading(false); return; } setLoading(true); setError(null); try { const [d, v] = await Promise.all([listDrivers(companyId), listVehicles(companyId, true)]); const [c, a] = await Promise.all([listComplianceForOwners('vehicle', v.map((x) => x.id)), listActiveVehicleDriversForVehicles(v.map((x) => x.id))]); setDrivers(d); setVehicles(v); setCompliance(c); setAssignments(a); } catch (e: any) { setError(e?.message ?? 'טעינת נתוני הדוחות נכשלה'); } finally { setLoading(false); } }, [companyId]);
  useEffect(() => { load(); }, [load]);
  const exportDrivers = async (category: ReportCategory) => { if (!company) return; setExporting(category); try { await exportDriversReport(company, drivers, category); setKind(null); } catch (e: any) { Alert.alert('ייצוא הדוח נכשל', String(e?.message ?? 'נסה שוב')); } finally { setExporting(null); } };
  const exportVehicles = async (category: VehicleReportCategory) => { if (!company) return; setExporting(category); try { await exportVehiclesReport(company, vehicles, compliance, assignments, category); setKind(null); } catch (e: any) { Alert.alert('ייצוא הדוח נכשל', String(e?.message ?? 'נסה שוב')); } finally { setExporting(null); } };
  return <View style={s.screen}><AdminGradientBackground /><View style={[s.header,{paddingTop:insets.top+18}]}><TouchableOpacity onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="chevron-forward" size={22} color="#102A42" /></TouchableOpacity><AppText weight="bold" style={s.title}>ייצוא דוחות</AppText><View style={s.spacer}/></View>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:<View style={s.content}><AppText style={s.hint}>בחר את סוג הדוח שברצונך להפיק</AppText><TouchableOpacity style={s.card} onPress={()=>setKind('drivers')}><View style={s.icon}><Ionicons name="people-outline" size={25} color="#0088CC"/></View><View style={s.copy}><AppText weight="bold" style={s.cardTitle}>דוחות נהגים</AppText><AppText style={s.cardSub}>רישיונות, תוקפים ונהגים ללא רכב</AppText></View><Ionicons name="chevron-back" size={19} color="rgba(16,42,66,.45)"/></TouchableOpacity><TouchableOpacity style={s.card} onPress={()=>setKind('vehicles')}><View style={s.icon}><Ionicons name="car-outline" size={25} color="#0088CC"/></View><View style={s.copy}><AppText weight="bold" style={s.cardTitle}>דוחות רכבים</AppText><AppText style={s.cardSub}>ביטוח, טסט, טיפולים וחריגות</AppText></View><Ionicons name="chevron-back" size={19} color="rgba(16,42,66,.45)"/></TouchableOpacity></View>}<ExportReportSheet visible={kind==='drivers'} title="ייצוא דוח נהגים" subtitle="בחר את קבוצת הנהגים לדוח" categories={REPORT_CATEGORIES} exportingCategory={kind==='drivers'?exporting as ReportCategory:null} onClose={()=>setKind(null)} onSelect={exportDrivers}/><ExportReportSheet visible={kind==='vehicles'} title="ייצוא דוח רכבים" subtitle="בחר את קבוצת הרכבים לדוח" categories={VEHICLE_REPORT_CATEGORIES} exportingCategory={kind==='vehicles'?exporting as VehicleReportCategory:null} onClose={()=>setKind(null)} onSelect={exportVehicles}/></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F1F4F7'},header:{paddingHorizontal:18,paddingBottom:18,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:21,backgroundColor:'rgba(255,255,255,.55)',alignItems:'center',justifyContent:'center'},spacer:{width:42},title:{fontSize:20,color:'#102A42'},content:{padding:18,gap:12},hint:{fontSize:14,color:'rgba(16,42,66,.65)',textAlign:'right',marginBottom:4},card:{backgroundColor:'rgba(255,255,255,.9)',borderRadius:22,padding:18,flexDirection:'row-reverse',alignItems:'center',gap:14},icon:{width:52,height:52,borderRadius:26,backgroundColor:'rgba(0,136,204,.1)',alignItems:'center',justifyContent:'center'},copy:{flex:1,alignItems:'flex-end'},cardTitle:{fontSize:17,color:'#102A42'},cardSub:{fontSize:13,color:'rgba(16,42,66,.6)',marginTop:3,textAlign:'right'}});
