import { StyleSheet } from 'react-native';
import { BRAND, COLORS, CONTENT_MAX_WIDTH, FONT, FONT_SIZE, SPACING } from '../../lib/theme';

/**
 * The shell shared by the phone driver and vehicle forms (DriverFormScreen,
 * VehicleFormScreen): halo, glass header with progress bar, hero card,
 * sections, footer CTA and the iOS date sheet. Each screen spreads this
 * into its own StyleSheet and adds only what differs.
 */
export const formScreenStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BRAND.screenBg },
  halo: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 300,
    maxWidth: CONTENT_MAX_WIDTH,
    marginHorizontal: 'auto',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    maxWidth: CONTENT_MAX_WIDTH,
    marginHorizontal: 'auto',
    zIndex: 5,
    overflow: 'hidden',
    backgroundColor: 'rgba(240,246,251,.72)',
    paddingHorizontal: 18,
    paddingBottom: SPACING.md,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(14,30,43,.06)',
  },
  headerTop: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 52,
  },
  headerTitle: { fontSize: FONT_SIZE.xl, lineHeight: 22, color: BRAND.ink },
  // Balances the back button; holds the small icar mark.
  headerSideSpacer: { width: 42, alignItems: 'center', justifyContent: 'center' },
  progressRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 2,
  },
  progressTrack: {
    flex: 1,
    height: 6,
    backgroundColor: 'rgba(16,31,44,.08)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  progressCounter: { width: 30, fontSize: FONT_SIZE.sm, fontFamily: FONT.bold, color: BRAND.ink, textAlign: 'right' },
  content: { paddingHorizontal: 18, gap: 20, width: '100%', maxWidth: CONTENT_MAX_WIDTH, alignSelf: 'center' },
  heroCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 18,
    paddingVertical: 12,
  },
  avatar: { position: 'relative' },
  avatarGradient: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.7)',
    shadowColor: COLORS.accent,
    shadowOpacity: 0.75,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 18 },
    elevation: 9,
  },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 3,
    borderColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroText: { flex: 1 },
  heroName: { fontSize: 26, letterSpacing: -0.8, color: BRAND.ink, marginBottom: 8 },
  heroBadges: { flexDirection: 'row-reverse', alignItems: 'center', gap: 9 },
  glassBadge: {
    minHeight: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,.75)',
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  glassBadgeText: { fontSize: FONT_SIZE.sm, color: BRAND.ink },
  section: { gap: 9 },
  sectionHeader: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  sectionDot: { width: 5, height: 5, borderRadius: 2.5, backgroundColor: COLORS.accent },
  sectionTitle: { fontSize: FONT_SIZE.sm, letterSpacing: 0.8, color: BRAND.inkSecondary },
  card: {
    backgroundColor: 'rgba(255,255,255,.92)',
    borderRadius: 24,
    borderWidth: 0.5,
    borderColor: 'rgba(16,31,44,.045)',
    shadowColor: BRAND.ink,
    shadowOpacity: 0.55,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 16 },
    elevation: 5,
    overflow: 'hidden',
  },
  rowFocused: { backgroundColor: 'rgba(0,136,204,.045)' },
  rowLast: { borderBottomWidth: 0 },
  focusRail: { width: 4, height: 22, borderRadius: 2, backgroundColor: 'transparent' },
  focusRailActive: { backgroundColor: COLORS.accent },
  labelFocused: { color: COLORS.accent },
  ltrInput: { textAlign: 'left', writingDirection: 'ltr' },
  checkBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(48,164,108,.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: {
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.lg,
  },
  cta: {
    height: 56,
    borderRadius: 19,
    backgroundColor: COLORS.accent,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  ctaText: { fontSize: FONT_SIZE.lg, color: '#FFFFFF' },
  ctaDisabled: { backgroundColor: 'rgba(118,118,128,.09)', shadowOpacity: 0, elevation: 0 },
  remainingText: { fontSize: FONT_SIZE.sm, color: BRAND.inkSecondary, textAlign: 'center', marginTop: 8 },
  dateSheetLayer: {
    ...StyleSheet.absoluteFill,
    zIndex: 7,
    justifyContent: 'flex-end',
  },
  dateSheetScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(16,31,44,.16)',
  },
  dateSheet: {
    marginHorizontal: 18,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,.96)',
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: 'rgba(16,31,44,.07)',
    shadowColor: BRAND.ink,
    shadowOpacity: 0.28,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  dateSheetHeader: {
    height: 50,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(14,30,43,.07)',
  },
  dateSheetTitle: { fontSize: FONT_SIZE.lg, color: BRAND.ink },
  dateSheetCancel: { fontSize: FONT_SIZE.lg, color: BRAND.inkSecondary },
  dateSheetConfirm: { fontSize: FONT_SIZE.lg, color: COLORS.accent },
  iosDatePicker: { alignSelf: 'center', height: 190 },
});
